--<ScriptOptions statementTerminator=";"/>
--DROP TABLE UTILISATEUR;
--DROP TABLE ETUDIANT_FORMATION;
--DROP TABLE ETUDIANT_ENTREPRISE;
--DROP TABLE FORMATION;
--DROP TABLE TYPEFORMATION;
--DROP TABLE ETUDIANT;
--DROP TABLE ENTREPRISE;


-- celui a utiliser pour la bd et non SIETUDIANTBD

CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50), SEQ_COUNT DECIMAL(15));
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0)


-- Creation des tables --
CREATE TABLE UTILISATEUR
(
LOGIN VARCHAR(150) NOT NULL,
MOTDEPASSE VARCHAR(150) NOT NULL,
NIVEAU INTEGER
);

CREATE TABLE ETUDIANT
(
IDETUDIANT BIGINT NOT NULL,
NOM VARCHAR(30) NOT NULL,
PRENOM VARCHAR(30) NOT NULL,
SEXE CHAR(10) NOT NULL,
NATIONALITE VARCHAR(30),
ADRESSE VARCHAR(150) NOT NULL,
CODEPOSTAL VARCHAR(6) NOT NULL,
TEL VARCHAR(30),
MAIL VARCHAR(30)

);

CREATE TABLE ENTREPRISE
(
IDENTREPRISE BIGINT NOT NULL,
NOM VARCHAR(150) NOT NULL,
RAISONSOCIALE VARCHAR(150),
SECTEURACTIVITE VARCHAR(150),
MAIL VARCHAR(150),
TEL VARCHAR(30)
);

CREATE TABLE ACTIVITE_PROFESSIONNELLE
(
IDACTIVITEPRO BIGINT NOT NULL,
IDETUDIANT BIGINT NOT NULL,
IDENTREPRISE BIGINT NOT NULL,
DATEDEBUT DATE NOT NULL,
DATEFIN DATE,
TYPECONTRAT VARCHAR(150),
POSTEOCCUPE VARCHAR(150),
DESCRIPTION VARCHAR(150),
COMMENTAIRE VARCHAR(150)
);

CREATE TABLE TYPEFORMATION
(
IDTYPEFORMATION BIGINT NOT NULL,
LIBELLE VARCHAR(150) NOT NULL
);

CREATE TABLE FORMATION
(
IDFORMATION BIGINT NOT NULL,
IDTYPEFORMATION BIGINT NOT NULL,
NOM VARCHAR(150) NOT NULL,
ETABLISSEMENT VARCHAR(150)
);

CREATE TABLE ETUDIANT_FORMATION
(
IDETUDIANT BIGINT NOT NULL,
IDFORMATION BIGINT NOT NULL,
ANNEE VARCHAR(4) NOT NULL
);

-- Ajout des contraintes pour chaque table --
ALTER TABLE UTILISATEUR ADD CONSTRAINT PK_UTILISATEUR PRIMARY KEY (LOGIN);
ALTER TABLE ETUDIANT ADD CONSTRAINT PK_ETUDIANT PRIMARY KEY (IDETUDIANT);
ALTER TABLE ENTREPRISE ADD CONSTRAINT PK_ENTREPRISE PRIMARY KEY (IDENTREPRISE);
ALTER TABLE TYPEFORMATION ADD CONSTRAINT PK_TYPEFORMATION PRIMARY KEY (IDTYPEFORMATION);
ALTER TABLE FORMATION ADD CONSTRAINT PK_FORMATION PRIMARY KEY (IDFORMATION);

ALTER TABLE ACTIVITE_PROFESSIONNELLE ADD CONSTRAINT PK_ACTIVITE_PROFESSIONNELLE PRIMARY KEY (IDACTIVITEPRO,IDETUDIANT,IDENTREPRISE);
ALTER TABLE ETUDIANT_FORMATION ADD CONSTRAINT PK_ETUDIANT_FORMATION PRIMARY KEY (IDETUDIANT,IDFORMATION,ANNEE);

ALTER TABLE ACTIVITE_PROFESSIONNELLE ADD CONSTRAINT FK_ACTIVITE_PROFESSIONNELLE_ETUDIANT FOREIGN KEY (IDETUDIANT) REFERENCES ETUDIANT (IDETUDIANT);
ALTER TABLE ACTIVITE_PROFESSIONNELLE ADD CONSTRAINT FK_ACTIVITE_PROFESSIONNELLE_ENTREPRISE FOREIGN KEY (IDENTREPRISE) REFERENCES  ENTREPRISE (IDENTREPRISE);

ALTER TABLE ETUDIANT_FORMATION ADD CONSTRAINT FK_ETUDIANT_FORMATION_ETUDIANT FOREIGN KEY (IDETUDIANT) REFERENCES ETUDIANT (IDETUDIANT);
ALTER TABLE ETUDIANT_FORMATION ADD CONSTRAINT FK_ETUDIANT_FORMATION_FORMATION FOREIGN KEY (IDFORMATION) REFERENCES FORMATION (IDFORMATION);

ALTER TABLE FORMATION ADD CONSTRAINT FK_FORMATION_TYPE_FORMATION FOREIGN KEY (IDTYPEFORMATION) REFERENCES TYPEFORMATION (IDTYPEFORMATION);

-- Ajouts pour d'eventuels tests --
INSERT INTO UTILISATEUR (LOGIN,MOTDEPASSE,NIVEAU) VALUES ('alex','534b44a19bf18d20b71ecc4eb77c572f',2);
INSERT INTO UTILISATEUR (LOGIN,MOTDEPASSE,NIVEAU) VALUES ('romain','5026bc63b5418ffdb54f238db245ec01',1);
INSERT INTO UTILISATEUR (LOGIN,MOTDEPASSE,NIVEAU) VALUES ('gerardo','4024fb06e1423da90b80f0274e8e4476',1);